# Generated by Django 5.1.7 on 2025-03-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_groups_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
