# Generated by Django 5.1.7 on 2025-03-20 11:05

import django.contrib.postgres.fields
from django.db import migrations, models, connection

def convert_jsonb_to_array(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE users_profile
            SET skills = jsonb_build_array(skills)
            WHERE jsonb_typeof(skills) = 'array';
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_location_alter_profile_skills_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_jsonb_to_array),
    ]
