# Generated by Django 5.1.7 on 2025-03-20 11:18

import django.contrib.postgres.fields
from django.db import migrations, models

def migrate_skills_jsonb_to_array(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    for profile in Profile.objects.all():
        #convert JSONB data to an array of strings
        if isinstance(profile.skills, list):
            profile.skills = [str(skill) for skill in profile.skills] # convert all items to string
        elif isinstance(profile.skills, dict):
            profile.skills = [f"{k}: {v}" for k, v in profile.skills.items()] # convert dict to key-value strings
        else:
            profile.skills = []
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_skills'),
    ]

    operations = [
        #step1: add a new temporary field
        migrations.AddField(
            model_name='profile',
            name='skills_temp',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), size=None, blank=True, null=True
            ),
        ),

        #step 2: copy data from old jsonb column to the new array field
        migrations.RunPython(migrate_skills_jsonb_to_array),

        #step3: remove old jsonb column
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),

        #step4: rename the new column back to "skills"
        migrations.RenameField(
            model_name='profile',
            old_name='skills_temp',
            new_name="skills",
        ),
    ]
